### ISSUE TITLE
Kernel keeps caching previous contents of mmaped files after ZFS snapshot rollback

### ISSUE THREAD

**Issue by tpwrules** [openzfs/zfs#10931]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Ubuntu
Distribution Version	| Groovy Gorilla Daily Build 2020-09-15
Linux Kernel	| 5.8.0-18-generic
Architecture	| amd64
ZFS Version	| 0.8.4-1ubuntu11
SPL Version	| 0.8.4-1ubuntu11

### Describe the problem you're observing
If a snapshotted file is modified through a memory map, then rolling back the dataset that file is on will not roll back the changes to the file; the file will appear as it was before the rollback. If the kernel caches are then dropped with `echo 3 > /proc/sys/vm/drop_caches`, then the file will (usually) appear as it was in the snapshot. Sometimes, the rollback must be attempted again before the file will appear correct.

### Describe how to reproduce the problem
The following console commands will reproduce the problem. Sample outputs are shown after each command.
```
# zfs create -o mountpoint=/cachetest rpool/ROOT/cachetest
# dd if=/dev/urandom bs=64K count=1 of=/cachetest/test.dat
1+0 records in
1+0 records out
65536 bytes (66 kB, 64 KiB) copied, 0.000907467 s, 72.2 MB/s

# zfs snapshot rpool/ROOT/cachetest@snap
# sha256sum /cachetest/test.dat 
a8020bbbeea430f0e01c611d8dc742bd658802e9fba39b3254cab0a98b66ff88  /cachetest/test.dat

change the file by flipping a bit through an mmap
# python3 -c 'import mmap; f = open("/cachetest/test.dat", "r+b"); mm = mmap.mmap(f.fileno(), 0); mm[0] ^= 1; mm.close(); f.close()'
# sha256sum /cachetest/test.dat 
436b172f281562f17c35e2208762241e9602940888f2bb8797ac6e4acc93b9ca  /cachetest/test.dat

# zfs rollback rpool/ROOT/cachetest@snap ; sha256sum /cachetest/test.dat 
436b172f281562f17c35e2208762241e9602940888f2bb8797ac6e4acc93b9ca  /cachetest/test.dat

# echo 3 > /proc/sys/vm/drop_caches ; sha256sum /cachetest/test.dat
a8020bbbeea430f0e01c611d8dc742bd658802e9fba39b3254cab0a98b66ff88  /cachetest/test.dat
```

### Include any warning/errors/backtraces from the system logs

No relevant logs were found.

**Comment by behlendorf** [comment]
I know @snajpa has been looking in to these kind of rollback issues.  This is a definitely a case we'll want to make sure gets handled correctly.

**Comment by shodanshok** [comment]
@behlendorf more generally, why ZFS does not block rollback if *any* file of the dataset is open? This can wreak havoc on application consistency. I would expect ZFS refusing to rollback a busy dataset the same as it refuse to delete a busy dataset.

**Comment by kneutron** [comment]
That is a very interesting question, I have long wondered what effect it would have on running VMs for instance...

**Comment by snajpa** [comment]
My understanding is, that the admin/user is responsible for evaluating, which services might cause problems and stopping them before the live rollback happens. It should be however doable without nasty side effects (like this bug); it blocks all the userspace software trying to access that dataset, until all of the visible VFS image, to the user space, is in the state of the snapshot. Only then the lock is released and applications are allowed to make VFS calls.

What could be nice to have, I think, would be some way, how to make apps compatible with live rollback, so they don't have to be first stopped manually - ie. make the barrier visible to userspace apps, somehow.

**Comment by behlendorf** [comment]
@shodanshok I think preventing the rollback would be a reasonable policy, however for whatever reason that's not how it was originally implemented on Solaris.  When it was ported to other platforms the goal was to honor those existing semantics.  However, clearly getting the behavior right for all the corner cases isn't easy.

**Comment by shodanshok** [comment]
@kneutron having tested this scenario (ie: active and busy virtual machines whose disk was suddenly rolled back), I can confirm that it cause a runaway corruption of the disk image (more precisely, of the filesystem running inside the image).

@snajpa I think this would be overwhelming complex for the virtual machine case, where the guest OS caches a now-obsolete view of the disk image.

@behlendorf now that Solaris and OpenZFS definitely have diverged, can this decision be reconsidered? It is possible to discuss it with the other main developers?

Thanks.

**Comment by tpwrules** [comment]
Is there any reason to believe this has been fixed yet? I will try to double check later if I remember.

**Comment by behlendorf** [comment]
This is still an issue.

**Comment by zviratko** [comment]
Just FYI we just hit this with v0.7.12 when rolling back snapshots for a tomcat application after a failed upgrade. I don't know whether java classloader does mmap(), but we had to drop_caches or we were getting corrupted .jar files on the dataset.

I don't think this is expected behaviour. Also, part of the application uses derby database, were such corruption happen here, it could go undetected for a long time (not sure how read-modify-write would look like with stale cache).

**Comment by zviratko** [comment]
@shodanshok in our today's case, nothing was opened. Application was shut down, two datasets were rolled back (one containing database, the other with tomcat, configuration and application) and the application was started - except it wasn't, because reading .jar files with classes returned garbage (or rather, it looked like a .jar file but couldn't be unzipped and had a different checksum to the snapshot).. echo 3 >/proc/sys/vm/drop_caches fixed it. This is real bad and not at all easy to find out. You don't expect a file that nothing ever writes to, with the same timestamp and the same size to return different contents. And you surely don't expect this to survive multiple (>5) rollbacks of the dataset.

**Comment by shodanshok** [comment]
@zviratko I missed that no files was open in your case. I totally agree that it is a very bad behavior, and should be fixed.

**Comment by cppudge** [comment]
Still reproducible on 2.3.9 (kernel 6.1.90, Debian-based), and it does **not** require the file to be modified *through* the mapping, nor any file to be open during the rollback. It is enough that pages of the file are resident in the page cache (i.e. the file was mmap'ed at some point) and the file is then modified with plain `write()`: `update_pages()` refreshes the resident pages, `zfs rollback` restores the DMU blocks, but the pages stay. After that both `read()` (via `mappedread()`) and `mmap()` return the pre-rollback data. `.zfs/snapshot/...` reads correctly (separate superblock, separate address_space), so on-disk data is fine.

We hit this in a CI setup that rolls a build-cache dataset back to a "golden" snapshot before each job: GCC mmap()s its `.gch` precompiled headers, ninja rewrites some of them during a job, and after the rollback the next job compiles against a mix of old and new 4K pages -> ICEs, `invalid preprocessing directive`, `sorry, unimplemented: PCH allocation failure`. Same size, same mtime, same inode, checksum differs from the snapshot; `zfs umount` + `zfs mount` (or `echo 1 > /proc/sys/vm/drop_caches`) fixes it.

Deterministic reproducer (100% for us, ZFS 2.1.11 and 2.3.9):

```python
#!/usr/bin/env python3
# Reproducer for openzfs/zfs#10931: stale page cache after `zfs rollback`.
# Usage: sudo python3 repro10931.py <pool>   (creates/destroys <pool>/repro10931)
import hashlib, mmap, os, random, subprocess, sys
pool = sys.argv[1]; ds = f"{pool}/repro10931"
mp = subprocess.check_output(["zfs", "get", "-H", "-o", "value", "mountpoint", pool], text=True).strip()
path, snap = f"{mp}/repro10931/f", f"{mp}/repro10931/.zfs/snapshot/s/f"
sha = lambda p: hashlib.sha256(open(p, "rb").read()).hexdigest()[:12]
subprocess.run(["zfs", "destroy", "-r", ds], stderr=subprocess.DEVNULL)
subprocess.check_call(["zfs", "create", ds])
with open(path, "wb") as f: f.write(random.randbytes(64 << 20))
subprocess.check_call(["zfs", "snapshot", f"{ds}@s"])
# 1. populate the page cache: mmap the file and touch every page
with open(path, "rb") as f, mmap.mmap(f.fileno(), 0, prot=mmap.PROT_READ) as m:
    sum(m[i] for i in range(0, len(m), 4096))
# 2. overwrite some pages with plain pwrite() -> update_pages() refreshes the cached pages
fd = os.open(path, os.O_WRONLY)
for p in random.sample(range(16384), 2000): os.pwrite(fd, random.randbytes(4096), p * 4096)
os.fsync(fd); os.close(fd)
# 3. roll back (mapping is already closed)
subprocess.check_call(["zfs", "rollback", "-r", f"{ds}@s"])
live, snapshot = sha(path), sha(snap)
print("live  :", live); print("snap  :", snapshot)
print("RESULT:", "OK" if live == snapshot else "STALE (live file != snapshot after rollback)")
subprocess.run(["zfs", "destroy", "-r", ds])
```

Output on unpatched 2.3.9:

```
live  : 43ba69eb75cf
snap  : 8ade6c3c0aca
RESULT: STALE (live file != snapshot after rollback)
```

Cause: on Linux `zfs_rezget()` (`module/os/linux/zfs/zfs_znode_os.c`), which `zfs_resume_fs()` calls for every surviving znode after a rollback/receive, reloads the SA attributes but never touches `ZTOI(zp)->i_mapping`. When object generation and size are unchanged and only data blocks differ, nothing invalidates the cached pages. The FreeBSD port handles exactly this case: its `zfs_rezget()` starts with `vn_pages_remove_valid(vp, 0, 0)` ("Remove cached pages before reloading the znode, so that they are not lingering...").

Adding the equivalent to the Linux version fixes it:

```c
	if (zp->z_is_ctldir)
		return (0);

+	truncate_inode_pages(ZTOI(zp)->i_mapping, 0);
+
	zh = zfs_znode_hold_enter(zfsvfs, obj_num);
```

With this the reproducer prints `OK` (7/7 runs, including a variant that keeps a live mapping across the rollback -- the mapping then faults the correct data back in through `zfs_getpage()`), and our CI has been clean since. PR: https://github.com/openzfs/zfs/pull/19013.
