### ISSUE TITLE
Fedora 38 zfs-testing repo is not available

### ISSUE THREAD

**Issue by yougotborked** [openzfs/zfs#14725]
### System information

Type | Version/Name
 --- | ---
Distribution Name	|Fedora
Distribution Version	|38
Kernel Version	|6.2.2-301
Architecture	|x86_64
OpenZFS Version	|2.1.9

### Describe the problem you're observing
zfs-testing repo for Fedora 38 is missing
### Describe how to reproduce the problem

```
dnf install https://zfsonlinux.org/fedora/zfs-release.fc38.noarch.rpm
gpg --import --import-options show-only /etc/pki/rpm-gpg/RPM-GPG-KEY-zfsonlinux
dnf config-manager --enable zfs-testing
dnf update
```

### Include any warning/errors/backtraces from the system logs
```
Errors during downloading metadata for repository 'zfs-testing':
  - Status code: 403 for http://download.zfsonlinux.org/fedora-testing/38/x86_64/repodata/repomd.xml (IP: 52.92.212.170)
Error: Failed to download metadata for repo 'zfs-testing': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
```

**Comment by yougotborked** [comment]
FYI I all I ended up doing to get zfs running on fedora 38 was
dnf install zfs --releasever=37 (this downgraded some packages). And the install failed to build due to the following bug in kernel 6.2.9
then I followed these steps.
https://github.com/openzfs/zfs/issues/14658#issuecomment-1489671067

```
[root@xwing zfs-2.1.9]# modinfo zfs | head
filename:       /lib/modules/6.2.9-300.fc38.x86_64/extra/zfs.ko.xz
version:        2.1.9-1
license:        CDDL
author:         OpenZFS
description:    ZFS
alias:          devname:zfs
alias:          char-major-10-249
srcversion:     1D0C47C31C2D5C103F4B022
depends:        spl,icp,zavl,znvpair,zcommon,zlua,zzstd,zunicode
retpoline:      Y
[root@xwing zfs-2.1.9]# 
```

**Comment by edgan** [comment]
Fedora 38 has now been released. I am interested in upgrading to it, and could use the dnf repository for zfs and Fedora 38.

**Comment by tonyhutter** [comment]
Quick update - I ran a first test of zfs-2.1.11 on Fedora 38 and it didn't go well:
```
Results Summary
PASS	 1269
FAIL	 119
SKIP	 204
KILLED	   5
```
I'll see if I can track down what's going on.  Hopefully it's just a configuration change or something simple.

**Comment by 0ranki** [comment]
> @edgan the plan is to build/release the F38 dkms packages once we're able to get a successful test run on F38. In the short term, you can use the zfs-2.1.10 F37 dkms packages on F38 as a stopgap.

For anyone interested, using the kwizart/kernel-longterm-6.1 kernel from https://copr.fedorainfracloud.org/coprs/kwizart/kernel-longterm-6.1/, and Fedora 37 zfs repo on Fedora 38 zfs-2.1.11 seems to be working well.

Steps to install:
```
dnf copr enable kwizart/kernel-longterm-6.1
dnf install kernel-longterm kernel-longterm-devel
# Optionally remove other kernels: dnf remove kernel-core-6.2.*
# reboot
# Edit /etc/yum.repos.d/zfs.repo and replace "$releasever" with 37
dnf makecache
dnf install zfs
modprobe zfs
```

Will keep following for progress though, but this seems a simple workaround for the time being.

**Comment by tonyhutter** [comment]
Some progress - I've now narrowed it down to only two real test failures:
```
Tests with results other than PASS that are unexpected:
    FAIL pam/pam_basic (expected PASS)
    FAIL pam/pam_nounmount (expected PASS)
```
Looking into those..

**Comment by tonyhutter** [comment]
Ok, we accounted for the test failures.  I pushed out the F38 RPMs now.

**Comment by seanjnkns** [comment]
@tonyhutter - were you going to push a new zfs-release for FC38?  There doesn't appear to be one, so it requires installing the FC37 one to pull down the FC38 packages, if you're already on FC38.

**Comment by edgan** [comment]
I upgraded my system that uses zfs to Fedora 38, and it works. Going to @seanjnkns's point, yes, the release package seems to be missing. I still have a fc37 release package.

**Comment by SimonGreenaway** [comment]
ZFS packages for FC38 are now available (mainstream not testing).

**Comment by tonyhutter** [comment]
@seanjnkns thanks for the heads-up on zfs-release - I just pushed it out:

```
rpm -e --nodeps zfs-fuse
dnf install -y https://zfsonlinux.org/fedora/zfs-release-2-3$(rpm --eval "%{dist}").noarch.rpm
dnf install zfs
```

**Comment by edgan** [comment]
I ran the command below and that did upgrade the release package on Fedora 38. But just doing a `dnf update` did not. It seems the package doesn't force an upgrade. Which it could with `epoch`.

```
dnf install -y https://zfsonlinux.org/fedora/zfs-release-2-3$(rpm --eval "%{dist}").noarch.rpm
```
