### ISSUE TITLE
Automatic ashift on pool creation fails with 32K sector size (regression)

### ISSUE THREAD

**Issue by IanCollins** [openzfs/zfs#18045]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Ubuntu
Distribution Version	| 24.04
Kernel Version	| 6.8.0-62-generic
Architecture	| X64
OpenZFS Version	| zfs-2.2.2-0ubuntu9.4

### Describe the problem you're observing
This is in a VM with a virtual drive with a sector size of 32K.

When creating a pool, the default ashift value of 9 is used instead of the correct value (15).

### Describe how to reproduce the problem
The disk:
```
$ sudo fdisk -l /dev/vdb
Disk /dev/vdb: 246 GiB, 264140488704 bytes, 515899392 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 32768 bytes
I/O size (minimum/optimal): 32768 bytes / 32768 bytes
Disklabel type: gpt
Disk identifier: 263B1FC9-C82C-F943-A7DE-555679A25777

Device         Start       End   Sectors  Size Type
/dev/vdb1       2048 515880959 515878912  246G Solaris /usr & Apple ZFS
/dev/vdb9  515880960 515897343     16384    8M Solaris reserved 1
```
The pool:
```
$ sudo zpool create -f mnt /dev/vdb
$ zpool status
  pool: mnt
 state: ONLINE
status: One or more devices are configured to use a non-native block size.
	Expect reduced performance.
action: Replace affected devices with devices that support the
	configured block size, or migrate data to a properly configured
	pool.
config:
	NAME        STATE     READ WRITE CKSUM
	mnt         ONLINE       0     0     0
	  vdb       ONLINE       0     0     0  block size: 512B configured, 32768B native
errors: No known data errors
$ sudo zdb -C mnt|grep ashift
                ashift: 9
```
Doing the same on Ubuntu 22.04, zfs-2.1.5-1ubuntu6~22.04.6
```
$ sudo zpool create -f mnt /dev/vdb
$ zpool status
  pool: mnt
 state: ONLINE
config:
	NAME        STATE     READ WRITE CKSUM
	mnt         ONLINE       0     0     0
	  vdb       ONLINE       0     0     0
errors: No known data errors
$ sudo zdb -C mnt|grep ashift
                ashift: 15
```

**Comment by amotin** [comment]
See `zfs_vdev_max_auto_ashift` parameter.

**Comment by IanCollins** [comment]
Thanks, that's a new one on me.  However, it does not get applied as I would expect; the value used is 9, not 14.

In addition, when the value applies is less than the sector size, the pool status warning will still be emitted: 
```
$ zpool status
  pool: mnt
 state: ONLINE
status: One or more devices are configured to use a non-native block size.
	Expect reduced performance.
action: Replace affected devices with devices that support the
	configured block size, or migrate data to a properly configured
	pool.
config:

	NAME        STATE     READ WRITE CKSUM
	mnt         ONLINE       0     0     0
	  vdb       ONLINE       0     0     0  block size: 16384B configured, 32768B native
```
Large sector sizes are probably rare.  In our case, the VM's disk is on a zvol on a raidz pool, so a larger volblocksize is used to maximise space efficiency!

In summary:
An incorrect value is used when the sector size is bigger than 16K (9 rather than `zfs_vdev_max_auto_ashift`).
Using a large sector size is most likely a deliberate choice, so the limit is not really required.

**Comment by amotin** [comment]
> However, it does not get applied as I would expect; the value used is 9, not 14.

This is intentional. If ZFS can not satisfy the hardware requirements, it should not even try, since it will add a space waste on ZFS layer, while still keeping the read-modify-write inside the device.

> In addition, when the value applies is less than the sector size, the pool status warning will still be emitted:

It was recently fixed in newer versions.

**Comment by IanCollins** [comment]
In our case, this was a surprise breaking change which will require a respin of our VM images, and that's never a good idea.  I still don't think this value is helpful, given the limited situations where a large sector size is encountered.

**Comment by amotin** [comment]
Those situations are not limited. There are modern NVMe SSDs reporting all kinds of physical sectors.  Not all of which are useful for ZFS to tune to.

**Comment by IanCollins** [comment]
One of those between a rock and a hard place situations. A compromise could be to emit the block size warning from zpool create as well as zpool status.
