### ISSUE TITLE
CentOS 7. Not mount/import pool after reboot

### ISSUE THREAD

**Issue by x09** [openzfs/zfs#2575]
Hi,

When power is turned off ZFS pool do not correctly export/unmount.
After reboot - "no datasets available"

 zfs-import-cache.service say:

авг 06 17:10:38 skynet zpool[2245]: cannot import 'STORE': pool may be in use from other system
авг 06 17:10:38 skynet zpool[2245]: use '-f' to import anyway
авг 06 17:10:38 skynet systemd[1]: zfs-import-cache.service: main process exited, code=exited, status=1/FAILURE
авг 06 17:10:38 skynet systemd[1]: Failed to start Import ZFS pools by cache file.

'zpool import STORE' say 'pool may be in use from other system'

 zpool import -f STORE work, but until next reboot. Then repeat again.

**Comment by yesbox** [comment]
There seems to be multiple issues. As seen in x09s logs, the imports were made by /dev/disk/by-vdev/.
Since I applied the /etc/hostid file fix mounting on boot has been working, until I started using aliases. I can reproduce this.

Using the default /dev/disk/by-id/ (mount at boot works):
```
[root]# zpool status
  pool: tank
 state: ONLINE
  scan: scrub repaired 0 in 0h2m with 0 errors on Fri Jan  2 21:26:54 2015
config:

        NAME                                        STATE     READ WRITE CKSUM
        tank                                        ONLINE       0     0     0
          ata-<RETRACTED>  ONLINE       0     0     0
```

Using /dev/disk/by-vdev/ (mount at boot fails):
```
/etc/zfs/vdev_id.conf:
#     by-vdev
#     name     fully qualified or base name of device link
alias d1       ata-<RETRACTED>

[root]# udevadm trigger
[root]# ls -al /dev/disk/by-vdev/
total 0
drwxr-xr-x. 2 root root 100 Jan 16 17:27 .
drwxr-xr-x. 7 root root 140 Jan 16 17:27 ..
lrwxrwxrwx. 1 root root   9 Jan 16 17:37 d1 -> ../../sda
lrwxrwxrwx. 1 root root  10 Jan 16 17:37 d1-part1 -> ../../sda1
lrwxrwxrwx. 1 root root  10 Jan 16 17:37 d1-part9 -> ../../sda9
[root]# zpool export tank
[root]# zpool import tank -d /dev/disk/by-vdev/
[root]# zpool status
  pool: tank
 state: ONLINE
  scan: scrub repaired 0 in 0h2m with 0 errors on Fri Jan  2 21:26:54 2015
config:

        NAME        STATE     READ WRITE CKSUM
        tank        ONLINE       0     0     0
          d1        ONLINE       0     0     0

errors: No known data errors
```
```
[root]# reboot
[root]# systemctl status zfs-import-cache.service
zfs-import-cache.service - Import ZFS pools by cache file
   Loaded: loaded (/usr/lib/systemd/system/zfs-import-cache.service; static)
   Active: failed (Result: exit-code) since Fri 2015-01-16 17:40:31 CET; 1min 25s ago
  Process: 562 ExecStart=/sbin/zpool import -c /etc/zfs/zpool.cache -aN (code=exited, status=1/FAILURE)
 Main PID: 562 (code=exited, status=1/FAILURE)

Jan 16 17:40:31 n54l zpool[562]: cannot import 'tank': no such pool or dataset
Jan 16 17:40:31 n54l zpool[562]: Destroy and re-create the pool from
Jan 16 17:40:31 n54l zpool[562]: a backup source.
Jan 16 17:40:31 n54l systemd[1]: zfs-import-cache.service: main process exited, code=exited, status=1/FAILURE
Jan 16 17:40:31 n54l systemd[1]: Failed to start Import ZFS pools by cache file.
Jan 16 17:40:31 n54l systemd[1]: Unit zfs-import-cache.service entered failed state.
```
The import command issued from the prompt works after boot. Mounting at boot works again after exporting and importing using the /dev/disk/by-id/ path instead of vdev.

**Comment by andyg5000** [comment]
After following @MagnusMWW steps and then running zpool export pool. I was able to reboot and have my pool auto-mounted. :)

**Comment by telsin** [comment]
I've hit this problem a system where I had to delay the zfs-cache-import for a few seconds because the ifs module hadn't finished loading yet. Similar to and same solution described https://bbs.archlinux.org/viewtopic.php?id=183851 (waitforzfsdevice script) worked for me on a centos 7.1 system. Others work fine though, so oddball timing in system...

**Comment by behlendorf** [comment]
This should now be addressed in master and the fix has been pulled in for the next port release.  As always, if someone who's able to regularly trigger this has time to verify the fix that would be welcome.

ba34dd9 Base init scripts for SYSV systems
544f718 Use ExecStartPre to load zfs modules
65037d9 Add libzfs_error_init() function

**Comment by telsin** [comment]
I still have the same problem as yesbox, I use vdev aliases and the mount at boot doesn't work (0.6.4.2-1, seems to have 544f718 in it). When I re-import the pool based on /dev/disk/by-path, it mounts fine at boot. My systemctl status logs are essentially identical to yesbox's when it fails.

**Comment by Bronek** [comment]
Last time I had a problem like this, changing HBA BIOS settings to wait 2s for each HDD helped.

**Comment by behlendorf** [comment]
Removing as a 0.6.5 blocker.  Using a stock CentOS 7 VM I'm unable to reproduce this issue.  However, since other have reported this issue I'm leaving it open.

```
$ uname -a
Linux burn 3.10.0-229.11.1.el7.x86_64 #1 SMP Thu Aug 6 01:06:18 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
$ reboot

...

$ systemctl status zfs-import-cache
zfs-import-cache.service - Import ZFS pools by cache file
   Loaded: loaded (/usr/lib/systemd/system/zfs-import-cache.service; static)
   Active: active (exited) since Fri 2015-09-04 18:58:52 EDT; 25s ago
  Process: 666 ExecStart=/sbin/zpool import -c /etc/zfs/zpool.cache -aN (code=exited, status=0/SUCCESS)
  Process: 644 ExecStartPre=/sbin/modprobe zfs (code=exited, status=0/SUCCESS)
 Main PID: 666 (code=exited, status=0/SUCCESS)

$ sudo zpool status -v
  pool: tank
 state: ONLINE
  scan: none requested
config:

	NAME                             STATE     READ WRITE CKSUM
	tank                             ONLINE       0     0     0
	  mirror-0                       ONLINE       0     0     0
	    virtio-758bc1f5-6d33-4bcb-b  ONLINE       0     0     0
	    virtio-3185b8f2-83ae-46f6-b  ONLINE       0     0     0
	logs
	  virtio-bf581023-3bc7-4750-b    ONLINE       0     0     0
	cache
	  virtio-7decbe42-ae05-4da9-9    ONLINE       0     0     0

errors: No known data errors
```

**Comment by telsin** [comment]
I see your pool uses /dev/disk/by-id names. That's what wound up working for me. I had problems when I was using vdev aliases though, did you try it that way?

**Comment by behlendorf** [comment]
@telsin no I didn't test with vdev aliases.  That's a good thought and I must have missed that in your comment.  When I get a chance to retest this again I'll use vdev aliases.

**Comment by danwestman** [comment]
Group:

Experiencing the same issue here, but I have a workaround that I figured I'd share.

System:
CentOS 7.1.1503 / 3.10.0-229.20.1.el7.x86_64
Pool #1 - Connected to motherboard SATA bus (no problems here)
Pool #2 - Connected to PCI SATA adapter (reliably will not mount at boot)

Workaround:

In file: /usr/lib/systemd/system/zfs-import-cache.service
Changed `ExecStart` to a custom script /<path>/foo.sh where foo.sh is like this:

```
#!/bin/sh

sleep 10
/sbin/zpool import -c /etc/zfs/zpool.cache -aN
```

I understand this may be an incorrect approach, but it was the only thing I could do that would reliably mount the second pool (attached to a PCI SATA controller).  Guessing it has to do with a delay between the module loading (as in `ExecStartPre=/sbin/modprobe zfs`) and the actual import script.

**Comment by Ralithune** [comment]
I had this problem today with CentOS 7 3.10.0-327.28.3, ZoL version 0.6.5.8-1.

Eventually I ended up typing "systemctl enable zfs-import-cache", and now the pool is present and mounted on reboot.

**Comment by shanghaiscott** [comment]
I updated to ZFS 0.6.5.8-1 from 0.6.5.7-1 and my pools stopped being imported and mounted on startup. After "systemctl enable zfs-import-cache", the pool imports, but is not mounted.

CentOS Linux release 7.2.1511 (Core)
kernel-3.18.34-20.el7.x86_64
zfs-0.6.5.8-1.el7.centos.x86_64
zfs-release-1-3.el7.centos.noarch
libzfs2-0.6.5.8-1.el7.centos.x86_64
zfs-dkms-0.6.5.8-1.el7.centos.noarch
spl-dkms-0.6.5.8-1.el7.centos.noarch
spl-0.6.5.8-1.el7.centos.x86_64

Message with prior ZFS:
Oct 31 19:30:30 localhost kernel: ZFS: Loaded module v0.6.5.7-1, ZFS pool version 5000, ZFS filesystem version 5
Oct 31 19:30:30 localhost systemd-modules-load: Inserted module 'zfs'
Oct 31 19:31:58 localhost systemd: Started Import ZFS pools by device scanning.
Oct 31 19:31:58 localhost systemd: Starting Import ZFS pools by cache file...
Oct 31 19:32:00 localhost systemd: Started Import ZFS pools by cache file.
Oct 31 19:32:00 localhost systemd: Starting Mount ZFS filesystems...
Oct 31 19:32:01 localhost systemd: Started Mount ZFS filesystems.
Oct 31 19:32:01 localhost systemd: Starting ZFS file system shares...
Oct 31 19:32:01 localhost systemd: Started ZFS Event Daemon (zed).
Oct 31 19:32:01 localhost systemd: Starting ZFS Event Daemon (zed)...
Oct 31 19:32:01 localhost zed: ZFS Event Daemon 0.6.5.7-1 (PID 3310)
Oct 31 19:32:01 localhost systemd: Started ZFS file system shares.
Oct 31 19:32:01 localhost systemd: Reached target ZFS startup target.
Oct 31 19:32:01 localhost systemd: Starting ZFS startup target.

Vs messages with latest ZFS RPMS:

Nov  1 12:28:41 localhost kernel: ZFS: Loaded module v0.6.5.8-1, ZFS pool version 5000, ZFS filesystem version 5
Nov  1 12:28:41 localhost systemd-modules-load: Inserted module 'zfs'
Nov  1 12:29:12 localhost systemd: Starting Import ZFS pools by cache file...
Nov  1 12:29:16 localhost systemd: Started Import ZFS pools by cache file.

The mount and subsequent messages never appear.

I have to run "zfs mount -a" to get the pool mounted

[root@thing1 ~]# zpool status -v
  pool: export
 state: ONLINE
  scan: none requested
config:

	NAME        STATE     READ WRITE CKSUM
	export      ONLINE       0     0     0
	  raidz2-0  ONLINE       0     0     0
	    raidzb  ONLINE       0     0     0
	    raidzc  ONLINE       0     0     0
	    raidzd  ONLINE       0     0     0
	    raidze  ONLINE       0     0     0
	    raidzf  ONLINE       0     0     0
	    raidzg  ONLINE       0     0     0
	logs
	  zil1      ONLINE       0     0     0
	cache
	  l2arc1    ONLINE       0     0     0

errors: No known data errors
I use device mapper names for the disks (which are whole disks, LUKS encrypted):

lrwxrwxrwx. 1 root root       7 Nov  1 12:29 /dev/mapper/raidzb -> ../dm-9
lrwxrwxrwx. 1 root root       7 Nov  1 12:29 /dev/mapper/raidzc -> ../dm-7
lrwxrwxrwx. 1 root root       8 Nov  1 12:29 /dev/mapper/raidzd -> ../dm-14
lrwxrwxrwx. 1 root root       8 Nov  1 12:29 /dev/mapper/raidze -> ../dm-10
lrwxrwxrwx. 1 root root       8 Nov  1 12:29 /dev/mapper/raidzf -> ../dm-12
lrwxrwxrwx. 1 root root       8 Nov  1 12:29 /dev/mapper/raidzg -> ../dm-13

**Comment by telsin** [comment]
Did you run

`systemctl preset zfs-import-cache zfs-import-scan zfs-mount zfs-share zfs-zed zfs.target`?

I missed it when I did some updates, reading the change log for 0.6.5.8 gave me that, no problems since.

**Comment by shanghaiscott** [comment]
That worked. Thanks!

Nov  1 14:46:30 localhost kernel: ZFS: Loaded module v0.6.5.8-1, ZFS pool version 5000, ZFS filesystem version 5
Nov  1 14:46:30 localhost systemd-modules-load: Inserted module 'zfs'
Nov  1 14:49:09 localhost systemd: Starting Import ZFS pools by cache file...
Nov  1 14:49:12 localhost systemd: Started Import ZFS pools by cache file.
Nov  1 14:49:12 localhost systemd: Starting Mount ZFS filesystems...
Nov  1 14:49:12 localhost systemd: Started Mount ZFS filesystems.
Nov  1 14:49:12 localhost systemd: Started ZFS Event Daemon (zed).
Nov  1 14:49:12 localhost systemd: Starting ZFS Event Daemon (zed)...
Nov  1 14:49:12 localhost zed: ZFS Event Daemon 0.6.5.8-1 (PID 4191)
Nov  1 14:49:12 localhost systemd: Starting ZFS file system shares...
Nov  1 14:49:12 localhost systemd: Started ZFS file system shares.
Nov  1 14:49:12 localhost systemd: Reached target ZFS startup target.
Nov  1 14:49:12 localhost systemd: Starting ZFS startup target.

**Comment by Loafdude** [comment]
I can recreate this error with latest CentOS / ZoL (0.7.1 as of posting)

1. Fresh Centos 7.4 minimal install
2. Follow ZoL instructions and add repository
3. Disable DKMS and enable kABI repositories
4. do a 'yum install zfs'

No hostid is created and
`systemctl preset zfs-import-cache zfs-import-scan zfs-mount zfs-share zfs-zed zfs.target`
must be run.

Sorry if this has been covered but this post helped me solve the issue.

**Comment by Loafdude** [comment]
I am sure.
My troubleshooting went as so;

1. Pools created on another machine would import but would not remount across reboots.
2. I created the /etc/hostid file.
3. The pools would then be 'not be found' and could not be imported.
4. I ran `systemctl enable zfs-import-cache` which allowed pools to be imported again. They still would not mount at boot.
5. I then ran `systemctl preset zfs-import-cache zfs-import-scan zfs-mount zfs-share zfs-zed zfs.target` and pools are now mounting at boot.

**Comment by sgembusch** [comment]
I am sure too.

CentOS 7.4/ZoL 0.7.3/DKMS: exactly the same problems (imported and new created pools are not mounted after reboot) and “solution” (`systemctl preset …`) as stated by @Loafdude

**Comment by jazzl0ver** [comment]
Faced same issue (thinking after upgrading to the latest kernel). Solution from @Loafdude does not work.
```
# uname -r
3.10.0-693.11.6.el7.x86_64
```
Also tried to *yum reinstall libzfs2 kmod-zfs zfs* - didn't help.
strace added to the ExecStart line in /usr/lib/systemd/system/zfs-mount.service displayed this after reboot:
```
...
622   access("/sys/module/zfs", F_OK)   = 0
622   access("/sys/module/zfs", F_OK)   = 0
622   open("/dev/zfs", O_RDWR)          = 3
622   close(3)                          = 0
622   open("/dev/zfs", O_RDWR)          = 3
622   open("/proc/self/mounts", O_RDONLY) = 4
622   open("/etc/dfs/sharetab", O_RDONLY) = -1 ENOENT (No such file or directory)
622   open("/dev/zfs", O_RDWR)          = 5
622   ioctl(3, _IOC(0, 0x5a, 0x04, 0x00), 0x7ffc8a71da80) = 0
622   ioctl(3, _IOC(0, 0x5a, 0x3f, 0x00), 0x7ffc8a71db90) = -1 EPERM (Operation not permitted)
622   close(3)                          = 0
622   close(4)                          = 0
622   close(5)                          = 0
622   exit_group(0)                     = ?
622   +++ exited with 0 +++
```
After the system booting completed manual call of *systemctl restart zfs-mount* does its job w/o issues..

Please, help!

**Comment by telsin** [comment]
See the release notes for 7.4 & 7.5, you probably need a "systemctl enable zfs-import.target"

**Comment by telsin** [comment]
check 'systemctl status zfs-import.target' and make sure it's enabled there and not just the preset.

**Comment by lamixer** [comment]
```
systemctl status zfs-import.target
● zfs-import.target - ZFS pool import target
   Loaded: loaded (/usr/lib/systemd/system/zfs-import.target; disabled; vendor preset: enabled)
   Active: inactive (dead)

systemctl enable zfs-import.target
Created symlink from /etc/systemd/system/zfs-mount.service.wants/zfs-import.target to /usr/lib/systemd/system/zfs-import.target.
Created symlink from /etc/systemd/system/zfs.target.wants/zfs-import.target to /usr/lib/systemd/system/zfs-import.target.

systemctl status zfs-import.target
● zfs-import.target - ZFS pool import target
   Loaded: loaded (/usr/lib/systemd/system/zfs-import.target; enabled; vendor preset: enabled)
   Active: inactive (dead)
```
We'll see how it goes on next reboot. Thanks.

**Comment by jasker5183** [comment]
Enabling zfs-import.target did the trick for me, which is weird because the first thing I tried was systemctl preset zfs-import-cache zfs-import-scan zfs-import.target zfs-mount zfs-share zfs-zed zfs.target. Am I to understand that zfs-import.target default is disabled?

**Comment by telsin** [comment]
As I understand it, the defaults only take effect on a new install and not on an upgrade, so it required manual intervention to enable. According to the release notes, this is supposedly fixed if 7.5, but if you went through 7.4, you got it without it being enabled and still needed to manually activate it. Not sure what happened to you @jasker5183, but if you went through 7.4 you may also have gotten it in a disabled state and needed to do it again.

**Comment by jazzl0ver** [comment]
@telsin , thank you very much! Enabling zfs-import.target did the trick!

**Comment by Merlin83b** [comment]
Running CentOS 7.4, ZoL 7.6 (updated from something much older), enabling zfs-import.target (it was disabled) didn't work for me.

I ended up doing
`cat /usr/lib/systemd/system-preset/50-zfs.preset|while read -r i; do systemctl $i; done`
which is probably not the systemd way, but worked for me.
