### ISSUE TITLE
resilvering of a device appears not to stop when the device is offlined?

### ISSUE THREAD

**Issue by phik** [openzfs/zfs#6570]
I looked through all 75 of the open resilver-related issues, but didn't see anything quite like this.

### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | CentOS
Distribution Version    | 7.3.1611
Linux Kernel                 | 3.10.0-514.6.1.el7.x86_64
Architecture                 | x86_64
ZFS Version                  | v0.7.1-1
SPL Version                  | v0.7.1-1

### Describe the problem you're observing

We have a four-device raidz3 pool.

At one point we noticed very weird performance problems and, suspecting a disk problem, took one of the devices offline.

6 or 8 weeks later, we decided to try to bring that disk online again.  Naturally, it began a lengthy resilver process.  100% disk utilisation doing writes to the 4th device, as expected.

After some time we decided that this wasn't worth the trouble, and took it back offline.  However, the resilver continues!  Sort of.

The 3 remaining devices are _still at 100% disk utilisation_!  Mostly reads, with a smattering of writes.  The 4th device (correctly) shows zero activity.

So what is it still resilvering?

"zpool status" shows that the offline device is still resilvering:

```
  scan: resilver in progress since Sat Aug 26 19:21:10 2017
        60.7G scanned out of 5.60T at 8.16M/s, 197h35m to go
        8.39G resilvered, 1.06% done
config:

        NAME                                   STATE     READ WRITE CKSUM
        lustre                                 DEGRADED     0     0     0
          raidz3-0                             DEGRADED     0     0     0
            ata-HGST_HUH721010ALE600_7PH35SUC  ONLINE       0     0     0
            ata-HGST_HUH721010ALE600_7PH36B6C  ONLINE       0     0     0
            ata-HGST_HUH721010ALE600_7PH377MC  ONLINE       0     0     0
            ata-HGST_HUH721010ALE600_7PH395GC  OFFLINE      0     0   584  (resilvering)
```

so, thinking that perhaps it simply wasn't smart enough to cancel, we rebooted the node, ensured that the disk was marked offline prior to import, and imported.  The result was that the resilver started right back up, it simply doesn't show "(resilvering)" after the 4th device any more:

```
  scan: resilver in progress since Sat Aug 26 19:21:10 2017
        182G scanned out of 5.60T at 12.1M/s, 130h40m to go
        8.39G resilvered, 3.17% done
config:

        NAME                                   STATE     READ WRITE CKSUM
        lustre                                 DEGRADED     0     0     0
          raidz3-0                             DEGRADED     0     0     0
            ata-HGST_HUH721010ALE600_7PH35SUC  ONLINE       0     0     0
            ata-HGST_HUH721010ALE600_7PH36B6C  ONLINE       0     0     0
            ata-HGST_HUH721010ALE600_7PH377MC  ONLINE       0     0     0
            ata-HGST_HUH721010ALE600_7PH395GC  OFFLINE      0     0     0
```

The "(amount) scanned" number keeps rising, as does the "% done".  But the "8.39G resilvered" remains constant (perhaps this is what it had managed to write to the 4th disk before it was taken back offline?)

Does this make sense to anyone?

From here, it seems like a case of "in-progress resilvering of a device that goes offline is continuing to do useless work"?  But maybe we're just not understanding what zpool status is trying to tell us?

**Comment by loli10K** [comment]
> I looked through all 75 of the open resilver-related issues, but didn't see anything quite like this.

https://github.com/zfsonlinux/zfs/issues/6076

**Comment by phik** [comment]
I see, yes, fair enough.  The subject didn't seem particularly relevant at the time, but now I see that this is one of the questions raised inside.

**Comment by loli10K** [comment]
Supposedly fixed in https://github.com/zfsonlinux/zfs/commit/d3f2cd7e3b70679f127dd471ea6d37ece27463f2.

**Comment by phik** [comment]
Not fixed, as far as I can tell.  Exactly the same situation, but now with v0.7.5-1.

This disk failed (we thought) and was replaced.  But now its replacement has also failed (or perhaps the SATA port or cables are bad).  Either way, it's still apparently resilvering a disk that's no longer there.

```
  scan: resilver in progress since Thu May 31 08:16:34 2018
        1.02T scanned out of 97.2T at 425M/s, 65h59m to go
        167M resilvered, 1.05% done
config:

        NAME                                   STATE     READ WRITE CKSUM
        lustre                                 DEGRADED     0     0     0
          raidz3-0                             DEGRADED     0     0     0
            ata-HGST_HUH728080ALE600_VLGXUV4Y  ONLINE       0     0     0
            ata-HGST_HUH728080ALE600_VLGZVG6Y  ONLINE       0     0     0
            ata-HGST_HUH728080ALE600_VLH1DHNY  ONLINE       0     0     0
            ata-HGST_HUH728080ALE600_VLH1KK3Y  ONLINE       0     0     0
            ata-HGST_HUH728080ALE600_VLH279KY  ONLINE       0     0     0
            ata-HGST_HUH728080ALE600_VLH2M9JY  ONLINE       0     0     0
            ata-HGST_HUH728080ALE600_VLH2PUWY  ONLINE       0     0     0
            ata-HGST_HUH728080ALE600_VLH2RNHY  ONLINE       0     0     0
            ata-HGST_HUH728080ALE600_VLH2VJHY  ONLINE       0     0     0
            replacing-9                        UNAVAIL      0     0     0  insufficient replicas
              3751375129735415788              OFFLINE      0     0     0  was /dev/disk/by-id/ata-HGST_HUH728080ALE600_VLH395SY-part1
              3738468069014060263              OFFLINE      0     0     0  was /dev/disk/by-id/ata-HGST_HUH728080ALE600_VLGPRAZY-part1
```

...and it continues to scan.

**Comment by phik** [comment]
(It doesn't look like I can reopen issues.  Should I file a new one?)

**Comment by dioni21** [comment]
This just happened to me.  Fedora 27, kernel 4.16.16-200.fc27.x86_64, zfs rpm **zfs-0.7.9-1.fc27.x86_64** from default repo http://download.zfsonlinux.org/fedora/$releasever/$basearch/

```
  pool: hgst
 state: DEGRADED
status: One or more devices is currently being resilvered.  The pool will
        continue to function, possibly in a degraded state.
action: Wait for the resilver to complete.
  scan: resilver in progress since Sun Jun 24 12:08:18 2018
        1.32T scanned out of 2.71T at 47.0M/s, 8h38m to go
        70.1G resilvered, 48.56% done
config:

        NAME                                         STATE     READ WRITE CKSUM
        hgst                                         DEGRADED     0     0     0
          mirror-0                                   DEGRADED     0     0     0
            ata-HGST_HDN724040ALE640_PK2334PEGV0BHT  REMOVED      0     0     0  (resilvering)
            ata-HGST_HDN724040ALE640_PK2334PEGYRTKT  ONLINE       0     0     0
        logs
          vg_ssd-z1_log                              ONLINE       0     0     0
        cache
          vg_ssd-z1_cache                            ONLINE       0     0     0

errors: No known data errors
```

To help debug: I'm dealing with a bad controller, that keeps disconnecting some disks, and this time it has disconnected again before resilvering has finished.

Kernel hacker here.  I'm happy to provide more debug information or tests, if anyone interested.

**Comment by behlendorf** [comment]
@dioni21 it would be great if you could provide a test case or at least a way to reliably reproduce this.  Then we'd be able to get a proper root cause on how this can happen and resolve it.

**Comment by dioni21** [comment]
@behlendorf first of all, **sorry** for not providing a test case before as you asked.  I run ZFS at home as main storage, and some testbed systems at work.  And I could not dedicate more time to the matter.

---

Not sure if it is the **SAME** issue, but something similar is happening to me now, and I'd like to register.

I had a 3 way mirror system.  In this system, one disk was showing some i/o errors.  I detached, cleaned and reattached the same disk.  Resilver started.

But I did not wait it to finish.  Attached another disk in the mirror.  After some time, both were in resilver state.

But still, too much I/O errors, and the whole system was slow.  A VM machine using a zvol device entered read-only mode.  So I try to stop this circus.

Detach one disk?  Command freeze (D state in proc table).  Detach the other?  Same.  Offline?  All four commands frozen.

Last try: delete SATA disk: `echo '1' >> /sys/block/${dev}/device/delete`

This has worked, and all commands unfroze.  But the pool continued in resilver state.

Ok, if I have to, let's reboot.

Now it like this:

```
  pool: tank
 state: ONLINE
status: One or more devices is currently being resilvered.  The pool will
        continue to function, possibly in a degraded state.
action: Wait for the resilver to complete.
  scan: resilver in progress since Fri Jun 11 09:42:58 2021
        4.94T scanned at 5.04G/s, 3.68T issued at 3.75G/s, 8.52T total
        0B resilvered, 43.18% done, 00:21:59 to go
config:

        NAME                                         STATE     READ WRITE CKSUM
        tank                                         ONLINE       0     0     0
          mirror-0                                   ONLINE       0     0     0
            ata-ST10000NM0016-1TT101_ZA22TBDD-part1  ONLINE       0     0     0
            ata-ST10000VN0004-1ZD101_ZA2BQQN3-part1  ONLINE       0     0     0
        special 
...
```

It's running.  Shouldn't it stop, since there are no more disks to resilver?  Also, `issued` speeds are unreal at my SATA system.  Maybe it is reading most from NVME special and memory cache.

Anyway, after some time the resilvering stopped, and a scrub started, as expected.

```
  scan: scrub in progress since Fri Jun 11 13:35:39 2021
        2.47T scanned at 2.62G/s, 180G issued at 191M/s, 8.52T total
        0B repaired, 2.07% done, 12:42:12 to go
```

Is this "zero device" resilver expected?  Or maybe another bug still lurking?

BTW: I'm currently running kernel `5.12.9-300.fc34.x86_64` and zfs `2.1.99-159_g2babd2004`

**Comment by mailinglists35** [comment]
@behlendorf here is a simple reproducer. resilver will NOT stop if you detach a not-finished-resilver disk.

`zpool attach pool dev newdev`
resilver starts
you change your mind midway: detach the newdev/phsyically disconnect the newdev/corrupt the newdev - anything just get it out of the pool
you even export and reimport the pool
absolutely nothing you do stands in the way of completing a full read of the pool by the `z_rd_int` resilver process.
there is no futher resilver that you can do until the old one completes reading the whole damn pool.

**Comment by mailinglists35** [comment]
this ofcourse would effectively immediately cancel/revert the effect other previous operations that kicked a resilver, such as attaching a new device

**Comment by bLuka** [comment]
Hello, thanks everyone for the tracking there,

I can confirm the annoying behavior. ZFS tried to resilver an end-of-life drive after a reboot, before resetting its faulty state.

However, resilver is still running after the drive state reverted to faulty, and even after completely offlining or removing it from the pool.

This is the worst-case scenario for the pool, as the mirror vdev is now a single drive with no redundancy, and is under very high load (resilver + regular load).
It is exponentially increasing the chances of the SPOF failing before being able to restore the mirror, and is even preventing the rebuild the mirror before the end of the first unsolicited resilver.
