### ISSUE TITLE
Receiving with -n flag reports that it would fail, even though it wouldn't

### ISSUE THREAD

**Issue by Infinisil** [openzfs/zfs#6773]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | NixOS
Distribution Version    | 18.03.git.7cf6e91b1d (Impala)
Linux Kernel                 | 4.9.56
Architecture                 | x86-64
ZFS Version                  | 0.7.2-1
SPL Version                  | 0.7.2-1

### Describe the problem you're observing

Using zfs receive -n with a -R stream being sent makes it output an error about the receiving filesystem missing, running it without -n works though.

This was also confirmed by @rincebrain with version 0.6.5.11.

### Describe how to reproduce the problem
```
$ zfs create foo/bar
$ zfs snap foo/bar@1
$ zfs snap foo/bar@2
$ zfs send -R foo/bar@2 | zfs recv -n baz
cannot receive incremental stream: destination 'baz' does not exist
$ zfs send -R foo/bar@2 | zfs recv baz
$ echo $?
0
```

**Comment by loli10K** [comment]
What is "baz" in your example? A ZFS pool? How does it look like before and after the successful `zfs recv baz`?

I usually find it useful to completely wipe my test pools when posting reproducers; so far i cannot reproduce you issue, probably because i don't have your same dataset tree configuration on my receiving end:

```
root@linux:~# cat /sys/module/zfs/version 
0.7.0-rc4
root@linux:~# # misc functions
root@linux:~# function is_linux() {
>    if [[ "$(uname)" == "Linux" ]]; then
>       return 0
>    else
>       return 1
>    fi
> }
root@linux:~# # setup
root@linux:~# POOLNAME='issue-6773'
root@linux:~# if is_linux; then
>    TMPDIR='/var/tmp'
>    mountpoint -q $TMPDIR || mount -t tmpfs tmpfs $TMPDIR
>    zpool destroy $POOLNAME
>    rm -f $TMPDIR/zpool_$POOLNAME.dat
>    fallocate -l 128m $TMPDIR/zpool_$POOLNAME.dat
>    zpool create -O mountpoint=none $POOLNAME $TMPDIR/zpool_$POOLNAME.dat
> else
>    TMPDIR='/tmp'
>    zpool destroy $POOLNAME
>    rm -f $TMPDIR/zpool_$POOLNAME.dat
>    mkfile 128m $TMPDIR/zpool_$POOLNAME.dat
>    zpool create $POOLNAME $TMPDIR/zpool_$POOLNAME.dat
> fi
root@linux:~# # 
root@linux:~# zfs create $POOLNAME/bar
root@linux:~# zfs snap $POOLNAME/bar@1
root@linux:~# zfs snap $POOLNAME/bar@2
root@linux:~# zfs send -R $POOLNAME/bar@2 | zfs recv -n baz ; echo $?
cannot receive new filesystem stream: destination 'baz' does not exist
1
root@linux:~# zfs send -R $POOLNAME/bar@2 | zfs recv baz ; echo $?
cannot receive new filesystem stream: destination 'baz' does not exist
1
root@linux:~#
```

**Comment by rincebrain** [comment]
baz is another pool, but it doesn't need to be, to reproduce this.

(monolith and workspace are just two pools I happen to have on the system.)

# zfs create monolith/foo
# zfs snapshot monolith/foo@1
# zfs snapshot monolith/foo@2
# zfs send -R monolith/foo@2 | zfs recv -nve workspace;
would receive full stream of monolith/foo@1 into workspace/foo@1
cannot receive incremental stream: destination 'workspace/foo' does not exist

**Comment by loli10K** [comment]
> baz is another pool, but it doesn't need to be, to reproduce this.

Somehow i think it does need to exists, to the very least, to reproduce this:

```
root@linux:~# zpool export -a
root@linux:~# zpool get guid baz
cannot open 'baz': no such pool
root@linux:~# # misc functions
root@linux:~# function is_linux() {
>    if [[ "$(uname)" == "Linux" ]]; then
>       return 0
>    else
>       return 1
>    fi
> }
root@linux:~# # setup
root@linux:~# POOLNAME='issue-6773'
root@linux:~# if is_linux; then
>    TMPDIR='/var/tmp'
>    mountpoint -q $TMPDIR || mount -t tmpfs tmpfs $TMPDIR
>    zpool destroy $POOLNAME
>    rm -f $TMPDIR/zpool_$POOLNAME.dat
>    fallocate -l 128m $TMPDIR/zpool_$POOLNAME.dat
>    zpool create -O mountpoint=none $POOLNAME $TMPDIR/zpool_$POOLNAME.dat
> else
>    TMPDIR='/tmp'
>    zpool destroy $POOLNAME
>    rm -f $TMPDIR/zpool_$POOLNAME.dat
>    mkfile 128m $TMPDIR/zpool_$POOLNAME.dat
>    zpool create $POOLNAME $TMPDIR/zpool_$POOLNAME.dat
> fi
cannot open 'issue-6773': no such pool
root@linux:~# # 
root@linux:~# zfs create $POOLNAME/bar
root@linux:~# zfs snap $POOLNAME/bar@1
root@linux:~# zfs snap $POOLNAME/bar@2
root@linux:~# zfs send -R $POOLNAME/bar@2 | zfs recv -n baz
cannot receive new filesystem stream: destination 'baz' does not exist
root@linux:~# zfs send -R $POOLNAME/bar@2 | zfs recv baz
cannot receive new filesystem stream: destination 'baz' does not exist
root@linux:~# zfs send -R $POOLNAME/bar@2 | zfs recv -nev baz
cannot receive: specified fs (baz) does not exist
root@linux:~# zpool import -d $TMPDIR baz
root@linux:~# zpool get guid baz
NAME  PROPERTY  VALUE  SOURCE
baz   guid      1245291995121516571  -
root@linux:~# zfs send -R $POOLNAME/bar@2 | zfs recv -n baz
cannot receive new filesystem stream: destination 'baz' exists
must specify -F to overwrite it
root@linux:~# zfs send -R $POOLNAME/bar@2 | zfs recv baz
cannot receive new filesystem stream: destination 'baz' exists
must specify -F to overwrite it
root@linux:~# zfs send -R $POOLNAME/bar@2 | zfs recv -nev baz
would receive full stream of issue-6773/bar@1 into baz/bar@1
cannot receive incremental stream: destination 'baz/bar' does not exist
root@linux:~# 
```

Also you are receiving with the `-e` option while the OP is not: is this reproducible regardless of the `-e` option?

**Comment by rincebrain** [comment]
Yes, baz itself needs to exist, in my example.

I can't obviously reproduce it without -e in quick testing, which does make some sense.

**Comment by loli10K** [comment]
@Infinisil can you please verify your reproducer is correct/working without the `-e` option (`zfs recv`)?

**Comment by Greek64** [comment]
Can confirm and reproduce.
It seems that `-R` goes from "replication stream" to "incremental stream" once the dataset should have been created and another snapshot exists before the selected one (source), and obviously fails since we are not actually creating anything (`-n` Flag).

Another example of reproduction:
```
# zfs create tank/child
# zfs snapshot tank/child@a
# zfs snapshot tank@b -r
# zfs send -R | zfs recv -n
```

**Comment by Infinisil** [comment]
Has been fixed at some point apparently, can't reproduce anymore!

**Comment by Ornias1993** [comment]
@Infinisil Thanks for reconfirming the issue! :)

**Comment by JanBeh** [comment]
I think this issue isn't resolved. When I use `-d`, I still encounter the issue:

```
# zfs version
zfs-2.2.0-FreeBSD_g95785196f
zfs-kmod-2.2.0-FreeBSD_g95785196f
# zfs create data/test
# zfs create data/test/A
# zfs create data/test/A/sub
# zfs snapshot -r data/test/A@s
# zfs send -R data/test/A@s > stream.zfs
# zfs create data/test/import
# zfs receive -v -n -F data/test/import < stream.zfs
would receive full stream of data/test/A@s into data/test/import@s
would receive full stream of data/test/A/sub@s into data/test/import/sub@s
# zfs receive -v -n -F -d data/test/import < stream.zfs
cannot open 'data/test/import/test': dataset does not exist
cannot receive new filesystem stream: unable to restore to destination
# zfs receive -v -F -d data/test/import < stream.zfs
receiving full stream of data/test/A@s into data/test/import/test/A@s
received 47.5K stream in 1.40 seconds (33.9K/sec)
receiving full stream of data/test/A/sub@s into data/test/import/test/A/sub@s
received 46.0K stream in 0.50 seconds (91.9K/sec)      
```
